### ISSUE TITLE
sidbar background color

### ISSUE THREAD

**Issue by mona9219** [YabataDesign/afterglow-theme#114]
sidebar of this theme not the same as the images its very light and ennoyable,but i love this theme how can i fix it?

**Comment by ryanderson** [comment]
Hi Mona9219 - you may just need to restart Sublime text and or add this line to the config file that opens when you select Preferences > Settings - User: "theme": "Afterglow.sublime-theme"

**Comment by mona9219** [comment]
i install it with git again and that problem fixed.
