### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by rpbaptist** [YabataDesign/afterglow-theme#120]
I see a lot of open PR's and no changes for 7 months.

If not, is there an active fork?

**Comment by egeerardyn** [comment]
@vikjam is maintaining a more active fork.

**Comment by jackolney** [comment]
Yep, @vikjam is maintaining the active fork -- would be good to get some more input on the package though; .R files are still missing icons for me.

**Comment by vikjam** [comment]
Hi @jackolney, could you open an [issue on the fork](https://github.com/vikjam/afterglow-theme/issues)? As a caveat, check to see if you're using the latest update of Afterglow. I did a fresh install of Sublime and theme, and it seems to be showing up for me.

Also, anyone who wants to access to become a contributor on the fork, feel free to let me know!

![screen shot 2015-12-26 at 11 29 59 am](https://cloud.githubusercontent.com/assets/1154799/12007689/9b076bfe-abc4-11e5-81c1-23c043adc022.png)

**Comment by rpbaptist** [comment]
Thanks! Should I close this issue?

**Comment by rpbaptist** [comment]
For anyone coming across this. This is the active fork:

https://github.com/AlpenglowTheme/alpenglow-theme
