### ISSUE TITLE
all afterglow-themes for vs code

### ISSUE THREAD

**Issue by sorooshafiee** [YabataDesign/afterglow-theme#131]
Hi

I am an old sublime text user, and I recently switched to vs code. I get used to your beautiful theme in sublime text. I was wondering whether is it possible to rewrite your extension for visual studio code, another open source text editor. There is two version of afterglow theme there but none of theme are similar to afterglow monokai theme that I was using :)

**Comment by egeerardyn** [comment]
This has been requested before in #128. As stated there, you might want to check out the AlpenGlow project since AfterGlow has been inactive for about 2 years now.

**Comment by bmcminn** [comment]
For reference https://packagecontrol.io/packages/Theme%20-%20Alpenglow
