### ISSUE TITLE
File icons like in predawn

### ISSUE THREAD

**Issue by varemenos** [YabataDesign/afterglow-theme#19]
Could you add filetype icons to the sidebar like in predawn?

**Comment by gj1118** [comment]
BUMP.. Even I would like to have this .. can you please let us know if you are going to work on this ? Please..

**Comment by daslicious** [comment]
+1

**Comment by YabataDesign** [comment]
Version 2.0.0 supports icons in the sidebar.

Sorry for the delay. 

Thanks so much!

**Comment by daslicious** [comment]
most excellent.
