### ISSUE TITLE
themes broken on Ubuntu

### ISSUE THREAD

**Issue by vivekmumbles** [YabataDesign/afterglow-theme#23]
The non-default themes no longer work in Sublime on Ubuntu 12.04.  The default theme seems to be working, but I had to revert to an older version of the __Afterglow-blue.sublime-theme__ file for it to work, so the problem must be in some recent change.

**Comment by digitalextremist** [comment]
No, this is happening with Sublime Text 3 also.

**Comment by digitalextremist** [comment]
Originally, I installed using Colorsublime versus the Package Manager directly. Is there a difference between the versions provided in either case? It's working with the version provided by the Package Manager, but not the one installed using Colorsublime.
