### ISSUE TITLE
Sidebar color is not changing in Ubuntu.

### ISSUE THREAD

**Issue by mitul45** [YabataDesign/afterglow-theme#32]
So I got this theme working perfectly except the sidebar color. That thing is still in light background.

**Comment by Mech7** [comment]
Not changing on mac either

**Comment by atuttle** [comment]
My sidebar was stuck at the previous theme until I restarted... but went all black (black text, black icons, on black background -- unusable) after restarting ST3. OSX 10.10.2, ST3 build 3065. Had to resort to a different theme, but I'm using the afterglow color scheme.

**Comment by mitul45** [comment]
Yup it worked for me to after restarting. So I think that is not an issue as of now.

**Comment by atuttle** [comment]
I disagree. I still get black on black on black -- unusable. I installed via ColorSublime, I wonder if that has anything to do with it.
