### ISSUE TITLE
Tabs are in italics.

### ISSUE THREAD

**Issue by gin93r** [YabataDesign/afterglow-theme#38]
Or they're emphasized. Either way, they're speaking to me in a shady manner or _really_ want me to pay attention to them.

Edit: Windows 7, SublimeText 2

**Comment by gin93r** [comment]
I was able to change this by modifying the Afterglo-orange.sublime-theme

But it would be nice if there was a setting for this instead.

**Comment by YabataDesign** [comment]
Please, show 2.1.0 release. 

Thanks so much.

**Comment by gin93r** [comment]
Works great. Thanks for the awesome theme @YabataDesign it's definitely my favorite so far.
