### ISSUE TITLE
Feature request: Dark blue background

### ISSUE THREAD

**Issue by fusion2004** [YabataDesign/afterglow-theme#43]
Would it be possible to add a version of the theme that uses the same dark blue background as Spacegray?
As seen here: 
![Spacegray ocean dark](https://raw.githubusercontent.com/kkga/spacegray/master/Screenshots/spacegray.png)

I tried just using the `base16-ocean.dark.tmTheme` color scheme from Spacegray, but I end up with this:
![screen shot 2015-03-14 at 1 59 43 pm](https://cloud.githubusercontent.com/assets/192395/6652812/6aa95df4-ca52-11e4-9083-c757be530308.png)

**Comment by YabataDesign** [comment]
Sorry, it is not possible. Afterglow is a theme based on gray colors. Spacegray is based in blue colors.

Thanks so much.
