### ISSUE TITLE
Is it possible to use the theme with normal tabs?

### ISSUE THREAD

**Issue by binaryanomaly** [YabataDesign/afterglow-theme#45]
Hi

This is really a beautiful sublime theme, very aesthetic, I like it a lot.

I'm however a bit optically "irritated" by the tabs. Is it possible to use the theme with the standard sublime tabs?

thx

**Comment by YabataDesign** [comment]
Sorry, Isn´t possible. Afterglow is a flat theme, and sublime theme default don't. 

Thanks so much.
