### ISSUE TITLE
Ruby icons

### ISSUE THREAD

**Issue by rlex** [YabataDesign/afterglow-theme#47]
Gemfile/Capfile/Ruby icon is barely visible and really differs from all other icons:
![screen shot 2015-04-03 at 21 41 27](https://cloud.githubusercontent.com/assets/84462/6986870/3f5adaf8-da4a-11e4-9301-4e65b821f306.png)
![screen shot 2015-04-03 at 21 37 01](https://cloud.githubusercontent.com/assets/84462/6986871/3f5d00a8-da4a-11e4-9b5c-0eb48c9be7ea.png)

**Comment by YabataDesign** [comment]
Yes, sorry. The retina icon was wrong. Thanks so much.
