### ISSUE TITLE
.erb files - ruby files

### ISSUE THREAD

**Issue by rlex** [YabataDesign/afterglow-theme#49]
erb files is some template with embedded ruby. Should also be with ruby icon. 
Will be nice if you can do this.
Pic:
![screen shot 2015-04-04 at 00 08 47](https://cloud.githubusercontent.com/assets/84462/6988966/e80c4a7e-da5e-11e4-9723-eb2ecc33955a.png)

**Comment by YabataDesign** [comment]
@kavu Thanks so much for the pull requests.
