### ISSUE TITLE
broken after 2.0.7

### ISSUE THREAD

**Issue by kimjinwuk** [YabataDesign/afterglow-theme#68]
![broke](https://cloud.githubusercontent.com/assets/6241336/7000407/a496f55a-dc5c-11e4-94a6-2be10d70d05a.jpg)

**Comment by primedirective** [comment]
Same problem! Totally broken after upgrade -- tried restarting sublime text 2.

**Comment by alex-hudenko** [comment]
Same problem. OS X Yosemite

**Comment by YabataDesign** [comment]
I uploaded an update: version 2.0.8. I hope this release solves the problem.

**Comment by owenhoskins** [comment]
2.0.8 fixed it for me, thanks!
