### ISSUE TITLE
Upgraded to 2.0.8: icons not displaying

### ISSUE THREAD

**Issue by dgmstuart** [YabataDesign/afterglow-theme#71]
Hi. I was previously running a version of the theme from before icons were added. 

On updating it went to version 2.0.8. On starting sublime I get these lines in my console:

```
loading pointer bindings
loading bindings
found 1 files for base name Afterglow.sublime-theme
Errors parsing theme:
Unknown attribute value
theme loaded
```

Therefore probably not the same issue as #56

I've tried removing and re-adding the theme, using different versions (base and blue) and using different colourschemes.

 I'm using version 2.0.2 of Sublime Text 2

**Comment by dexterchua19** [comment]
Same issue here. Not showing icons on sidebar after the update and showing the same message on console

**Comment by chaserx** [comment]
Same issue... seems to work in Sublime Text 3 though.

**Comment by dgmstuart** [comment]
Sounds like icons are only supported in Sublime Text 3. I suggest the 'fix' is just to make this explicit in the readme.
