### ISSUE TITLE
Opening .dockerfiles crashes sublime.

### ISSUE THREAD

**Issue by 7imbrook** [YabataDesign/afterglow-theme#73]
Versions:
OS X 10.10.3, sublime 3083, afterglow v2.0.8

Crashlog:
http://pastebin.com/1rQJjtmq

Workaround:
Leave the crashlog window open and reopen sublime. It doesn't really crash sublime unless you try to reopen the .dockerignore. But if you do it once, the crash dialog will keep popping up with a kernel permissions error UNLESS you leave the window open (probably just suppresses it).

**Comment by brismuth** [comment]
Pretty sure this is related to issue [#67](https://github.com/YabataDesign/afterglow-theme/issues/67). I've described a work around in that thread that isn't too bad. It should hopefully work for you too.

**Comment by kavu** [comment]
Could you check my fix in #75?

**Comment by 7imbrook** [comment]
Also why is the source set to dockerfile? Its an ignore file, isn't dockerfile for the Dockerfile? Can we just use plaintext and gitignore?

**Comment by YabataDesign** [comment]
Sorry for the delay. I upgraded to version 2.0.9. I hope this update fix the issue.
