### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by Thomasdezeeuw** [YabataDesign/afterglow-theme#77]
I've been happily using this theme for a while now, and I think it's great. But this last two weeks or so every update seems to break something. It's really annoying considering the time I spend in my editor and I would rather not add time to it by fixing the theme every day.

The latest change broke my theme again and now I can't even find a way to fix it. All the colours back to the (I think) default.
/rant

But again I really like the theme, well done.

**Comment by robjens** [comment]
Same here... just broke my side bar turning it light instead of dark. Why? This was the instant after the theme was automatically updated... annoying contrast

**Comment by simonsmith** [comment]
Mine is also broken when booting Sublime today

http://cl.ly/acj9

**Comment by simonsmith** [comment]
Interestingly I'm seeing this issue without Afterglow. A fresh install of Sublime plus Space Gray and it looks fine. Once I add all my other packages back in (minus Afterglow) I see the white project drawer again. Maybe another package has pushed a breaking change?

Be interested to see what other people report

**Comment by simonsmith** [comment]
So, after some playing around it seems that my `color_scheme` and `theme` entries in preferences were changed. Not sure how. I reinstalled the theme and set those values to match the documentation and it's working again fine

**Comment by Thomasdezeeuw** [comment]
Completely removing and reinstalling Sublime seems to fix the issues for aswell.
