### ISSUE TITLE
suggestion: add sidebar icon support for directory / folder

### ISSUE THREAD

**Issue by fyears** [YabataDesign/afterglow-theme#79]
We know that many file types comes with sidebar icons in afterglow-theme.

But directories / folders do not have icons.

For the reason of "symmetry", why not add sidebar icon support for directory / folder (is it possible?)? Something like this one: :file_folder:

Thanks. :-)

**Comment by andmm** [comment]
+1 on this.

This theme is really one of the best but I really dislike the +/-.

A toggle for folder icons would be great
