### ISSUE TITLE
Folder plus/minus Missing

### ISSUE THREAD

**Issue by bbeckford** [YabataDesign/afterglow-theme#85]
After the package updated sometime over the weekend the plus/minus icons on folders in the side bar have disappeared.

Using Sublime 2.0.2 Build 2221

![Example of no folder plus/minus](http://i.imgur.com/iZqmaWu.png)

**Comment by TheFox** [comment]
Same here. This is since Afterglow v2.1.1.

**Comment by bbeckford** [comment]
Replacing Afterglow-blue.sublime-theme with the previous version does repair the issue so it's definitely something introduced in the last commit.

I'd create a pull request by my knowledge of sublime theming is pretty limited!

Thanks

**Comment by TheFox** [comment]
> Replacing Afterglow-blue.sublime-theme with the previous version does repair the issue

Unfortunately not. I tried it too.

**Comment by turbometalskater** [comment]
I see that many lines removed on pull request #83 are relatives to theme sections:
- Sidebar group closed
- Sidebar folder closed
- Sidebar group open
- Sidebar folder open

from commit tagged 2.1.0 (not included) to origin/HEAD all the +/- icons are missing :( 
(tested on subl2)

**Comment by bbeckford** [comment]
> Unfortunately not. I tried it too.
> - TheFox

That's strange, it worked for me. Are you using the blue theme? If not did you try with the right theme colour file?

**Comment by TheFox** [comment]
No, I tried it with default theme on Sublime Text 2.

**Comment by jpark1120** [comment]
I am having the same issue on sublime text 2 (v2.0.2, Build 2221) after package updated.

**Comment by pajenkin** [comment]
I am having the same issue. I am working with Sublime Text 2 (v2.0.2, Build 2221).

**Comment by indri-indri** [comment]
My latest commit causes this. 

I didn't know the sidebar icons were missing in Sublime Text 2, and my solution to issues #82 and #79 was to change the expand-button to the space where the icons would be in.

Knowing this, the poor alignment issues turn out to be really hard to fix without removing the icons.

I would like to ask @YabataDesign to revert the changes until we find a solution that works for everyone.
Apologies.

**Comment by gin93r** [comment]
I have also experienced this with ST2.

**Comment by extractachris** [comment]
+1. ST2.
