### ISSUE TITLE
"sidebar_no_icon" option no longer disables sidebar icons

### ISSUE THREAD

**Issue by minusfive** [YabataDesign/afterglow-theme#86]
Looks like after the latest update the "sidebar_no_icon" option has no effect.

**Comment by igregson** [comment]
Also having this problem...

**Comment by spitalia** [comment]
+1

**Comment by CookPete** [comment]
Yep, me too.

**Comment by wontaeyang** [comment]
Me as well

**Comment by shivapoudel** [comment]
:worried: me too xD

**Comment by JediSange** [comment]
This started happening for me as well.  I tracked it to this commit: b34ffbe45a045475a55473667ce8e1866fbfb5c3  Working on a fix now.

**Comment by honi** [comment]
Please fix! Theme is great but icons are very distracting.

**Comment by mikefrancis** [comment]
Just giving this a bump - when can we anticipate a fix?
