### ISSUE TITLE
windows italic tabs

### ISSUE THREAD

**Issue by mickey-megabyte** [YabataDesign/afterglow-theme#96]
Hi, love this theme, and I enjoy the range of options so I can customize it my way.

One thing that puzzles me is why you have a special option for windows tab labels.

I use sublime on both windows and linux, and on both systems the tab labels are only italic if you are previewing files (ie only one click in sublime sidebar).  If you actually properly open them (double-click sidebar), then the tab label is not italic.

So, I don't think you need this option.  :)

**Comment by YabataDesign** [comment]
For this issue: https://github.com/YabataDesign/afterglow-theme/issues/38

Thanks!
