### ISSUE TITLE
Move close buttons to the left side of the tab (OS X-style)

### ISSUE THREAD

**Issue by inket** [YabataDesign/afterglow-theme#97]
Hey,

This should be doable I think. It would be great to have the option because right now I'm used to another theme which had the close buttons on the left side and I keep accidentally closing tabs.

Thank you.

**Comment by YabataDesign** [comment]
Hi,

What theme has the close buttons on the left side? I don't know how do this.

Thanks so much.

**Comment by inket** [comment]
Turns out I was completely wrong. My memory failed me. I don't know of any theme with the close buttons on the left side. It's probably impossible.

Sorry for the confusion.
